### ISSUE TITLE
Issue using WB-700-IPV-12

### ISSUE THREAD

**Issue by officialJCReyes** [bitfocus/companion-module-snapav-wattbox#2]
When I select this unit from the drop-down menu, I can only configure outlets 1-3. I don't have an option to select additional ports. 
Ports 1-3 work normally.

NOTE: The issue appears to be ONLY when using the Power Cycle option. When using Power (on/off) I see all 12 ports and they can be controlled with no issue.

![wattbox issue 1](https://user-images.githubusercontent.com/13990650/176066713-948aad60-649f-4f40-a859-1e28426fd9a7.png)

![wattbox issue 2](https://user-images.githubusercontent.com/13990650/176066727-91e69caa-5756-4b1a-9cfb-ae57802bc86e.png)

**Comment by JTF4** [comment]
@officialJCReyes this should be fixed in the newest release in V3. Sorry it took a year to get to!
